version: '3'
services:
  jupyter:
    build: 
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ../:/home/notebook
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"