version: '3'
services:
  jupyter:
    build: 
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ../programming_notebooks:/home/notebook
    ports:
      - 8888:8888
    command: "start-notebook.sh --NotebookApp.token="